### ISSUE TITLE
The GitHub action of awesome-flutter-desktop no longer works

### ISSUE THREAD

**Issue by schilken** [leanflutter/awesome_list_maker#1]
The newest version of pub_api_client no longer has the method pubPackage.toJson(). Therefore the action is aborted, and the new readme isn't created.

https://github.com/leanflutter/awesome-flutter-desktop/actions/runs/4279922400/jobs/7451119728

I would set the package version to 2.2.2 in the pubspec.yaml. That is the version before: **Removed freezed**

**Comment by lijy91** [comment]
I have set to 2.1.0
